--- 
excluded_pkgfiles: []

project_pubdir: /usr/local/www/public/code
project_pubhost: deveiate.org
project_homepage: http://deveiate.org/projects/Ruby-LinkParser/
gem_pubhost: rubygems.org
project_requirements: 
  link-grammar: ">= 4.7.0"
release_smtphost: mail.faeriemud.org
project_licenses: 
- BSD
project_description: |-
  A Ruby binding for the link-grammar library, a syntactic parser
  of English. See http://www.link.cs.cmu.edu/link/ for more
  information about the Link Grammar, and
  http://www.abisource.org/projects/link-grammar/ for information
  about the link-grammar library.
release_mailto: Ruby-Talk List <ruby-talk@ruby-lang.org>
project_dependencies: {}

project_summary: a Ruby binding for the link-grammar library
version_file: linkparser.rb
additional_pkgfiles: []

required_ruby_version: ">=1.8.7"
dev_dependencies: 
  rake-compiler: ~> 0.7.1
authors: 
  Martin Chase: stillflame@FaerieMUD.org
  Michael Granger: ged@FaerieMUD.org
post_install_message: ""
project_name: LinkParser
