--- 
rubyforge_project: linkparser
project_requirements: 
  link-grammar: ">= 4.4.1"
project_pubdir: /usr/local/www/public/code
project_description: |-
  A Ruby binding for the link-grammar library, a syntactic parser
  of English. See http://www.link.cs.cmu.edu/link/ for more
  information about the Link Grammar, and
  http://www.abisource.org/projects/link-grammar/ for information
  about the link-grammar library.
rubyforge_group: deveiate
author_name: Michael Granger
project_pubhost: "deveiate.org"
project_homepage: http://deveiate.org/projects/Ruby-LinkParser/
project_dependencies: {}

project_summary: a Ruby binding for the link-grammar library
project_name: LinkParser
version_file: linkparser.rb
additional_pkgfiles: []
dev_dependencies: {}

author_email: ged@FaerieMUD.org
post_install_message: ""
